# Generated by Django 4.1a1 on 2022-06-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_borrower_alter_bookinstance_imprint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'установить книгу как возвращенную'),), 'verbose_name': 'экземпляр книги', 'verbose_name_plural': 'экземпляры книг'},
        ),
    ]
